#
# ARMSCII-8 Compose Sequence
#
# Sequence Definition
#
#
# This file currently has no entries.  It appears that a compose file (even
# just an empty one) is required for the appropriate keysyms to work for
# this enc